language: rust
cache: cargo
sudo: false
rust:
  - stable
addons:
  apt:
    packages:
      - flex
before_script:
  - flex --version
jobs:
  include:
    - stage: test
      script: cargo test
    - script: cd telamon-utils && cargo test
    - script: cd telamon-gen && cargo test
    - script: cd telamon-gen/cc_tests && cargo test
    - script: cd kernels && cargo test --release
    - script: cd telamon-gen && LEX="flex" cargo build --features "lex"
    - script: cargo fmt --all -- --check
      before_script: rustup component add rustfmt-preview
    - stage: documentation
      if: branch IN (master, staging)
      script: cargo doc --no-deps --all
      deploy:
        provider: pages
        local-dir: target/doc
        target-branch: gh-pages
        skip-cleanup: true
        keep-history: true
        github-token: "$GITHUB_TOKEN"
