language: rust
cache: cargo
sudo: false
os:
  - osx
  - linux

rust:
  - nightly-2018-04-03
#  - nightly

#matrix:
#  allow_failures:
#    - rust: nightly

before_install:
  - git config user.name $(git log -1 --pretty="%an")
  - git config user.email $(git log -1 --pretty="%ae")

install:
  - cargo +$TRAVIS_RUST_VERSION install --force rustfmt-nightly
  - rustfmt src/lib.rs

before_script:
  - rustc --version
  - cargo --version

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --verbose --all

deploy:
  - provider: pages
    local-dir: target/doc
    target-branch: gh-pages
    skip-cleanup: true
    keep-history: true
    github-token: "$GITHUB_TOKEN"
  - provider: pages
    local-dir: .
    target-branch: master
    skip-cleanup: true
    keep-history: true
    github-token: "$GITHUB_TOKEN"

env:
  global:
    secure: T7ao3Xly60lrporBe0RChgoqLAQ8OGegUHYmQ6ZQJJqRwKansrJkd0S4w6ZtLYMqzwX03ycI+B9euPY0km3uSxysssBNJamqLyw2my9+zIOR31+6rP/+MeH1/GPcvJF5foGZAoLwxxIp+wF/5FvsqhgpfoIT1GHDylMKFGuq9lleWc1i03xAV341avjRMi9O23fEpAHEixlXl0rIGl1k6PeUy0nP0bktxk+0Z1pFdi89w3EfCSE5GESWQhylB+vI2CHFDj7rTAMRO1J5KYEcXjpKGPpdYdmJz7Egp3qimIzdNUiIJxEJOdXUtys2thuf/R8r/neGiP757OX/MDJ0DT7sxqmKeF85BTc8X2KjPgRcjOsSXL5xEmkgRm9UaR2qiBrvpCxCM0EIoIUADMwDbMUCpNzWrPGFCL6SxR8zDc9/aSUWr2Mt41MX7oNWxViQLQACIuh5xnved8c01gsseBCUkyMXybisiZtNts/AolBS5Ayu/qAp0ocZn9xKy7pCxSmLNfl7EVozEjDI8qegv23apqdseGNv2QtR5vM7t4SYsNnBsQosoC5DIICy7BiX0fboKP1qKHFMhJGekka3ky9/wCHbaZb205PLZ9GxEkHVfuOxsFOdszglGZtknvKqdwnxt04gqs33iL6o/1GGOcRiEdvOqhWWrbz+nMUQqV8=
